### ISSUE TITLE
Will this still be maintained?

### ISSUE THREAD

**Issue by quantuminformation** [gothinkster/gcp-datastore-cloud-functions-realworld-example-app#42]
I now have locally emulation of everything set up and could add a PR for this. However, I am not sure what the plan is for this repo going ahead. Will, it still be maintained or will I maintain my own fork/clone of it.

you can see the local emulation in here:

https://www.youtube.com/watch?v=7LqkLTGR54E

**Comment by anishkny** [comment]
Yes this is being maintained.

**Comment by quantuminformation** [comment]
Great to hear!
