### ISSUE TITLE
Enable CORS

### ISSUE THREAD

**Issue by sharadkap** [gothinkster/gcp-datastore-cloud-functions-realworld-example-app#6]
Hi,

I am trying to add CORS to this app and could really find the best way of having Access-Control-Allow-Origin as I am running the frontend on localhost:4200. All of my requests are being blocked in GCP. 
I am trying to figure out where should I add the CORS. (Sorry, I am quite new to Nodejs and this may seem a silly question) 

I was reading this
https://github.com/expressjs/cors
and then this 
https://github.com/gothinkster/realworld/tree/master/api

which says I need to use OPTIONS to return correct headers. 
I have this in my code in the Router.js

`const headers = {};
    headers["Access-Control-Allow-Origin"] = "*";
    headers["Access-Control-Allow-Methods"] = "POST, GET, PUT, DELETE, OPTIONS";
    headers["Access-Control-Max-Age"] = '86400'; // 24 hours
    headers["Access-Control-Allow-Headers"] = "Authorization, X-Requested-With, X-HTTP-Method-Override, Content-Type, Accept";
`

and also having a check

`if (req.method === 'OPTIONS') {
        res.writeHead(200, headers);
        res.send();
      }
`

But my app still throws the error

Failed to load https://my-app/api/tags: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access.

Any help would really be appreciated. 

Thanks!

**Comment by anishkny** [comment]
I added code to enable CORS. Could you try it out?

https://github.com/gothinkster/gcp-datastore-cloud-functions-realworld-example-app/commit/0fb191af07e464dada02708322483581508fd536

**Comment by sharadkap** [comment]
Thanks mate for your prompt response. I will give it a try now. :)

**Comment by anishkny** [comment]
@sharadkap does this change make the frontend work? Please submit a PR with your changes by following instructions [here](https://help.github.com/articles/creating-a-pull-request-from-a-fork/). And thanks for your help!

**Comment by sharadkap** [comment]
Thanks @anishkny - No worries. Yes, this change made the frontend working fully across all the HTTP method types. I have added this at the top level. 
I will follow the PR instructions and we will take it from there. 👍

**Comment by sharadkap** [comment]
Thanks @anishkny - looks like you already made that change. I was away for a few days.

**Comment by anishkny** [comment]
Yes. Could you verify for your use case?

**Comment by sharadkap** [comment]
Hey Anish, yes its works now with this one as well. Thanks for your help.

**Comment by quantuminformation** [comment]
I'm finding when trying to unfavourite an article I get

Access to fetch at 'http://localhost:8080/articles/2-qkgw8q/favorite' from origin 'http://localhost:3000' has been blocked by CORS policy: Method DELETE is not allowed by Access-Control-Allow-Methods in preflight response.

this didn't help

```js
 // Enable CORS
    res.set('Access-Control-Allow-Origin', '*')
      .set("Access-Control-Allow-Methods", "GET", "PUT", "POST", "DELETE", "OPTIONS")
      .set('Access-Control-Allow-Headers', req.header('Access-Control-Request-Headers'));
```

**Comment by quantuminformation** [comment]
Adding this fixed it

```
    res.setHeader(
      "Access-Control-Allow-Methods",
      "GET, POST, PATCH, DELETE, OPTIONS"
    );```
